# -*- coding: utf-8 -*-
"""Oort_FL_Fixed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uUgnxxdpcsVrHON5q1Kw-lq2cC17YfK-

# 🌸 Oort Strategy — Federated Learning
### Reproducing *Oort: Efficient Federated Learning via Guided Participant Selection* (OSDI 2021)

**Group Task:** Reproduce Oort and compare against FedAvg baseline  
**Framework:** Flower (`flwr`) simulation mode  
**Datasets:** MNIST, FashionMNIST, CIFAR-10  
**Clients:** 10, 50, 100  
**Partitioning:** Dirichlet α ∈ {0.01, 0.1, 0.5, 1.0, IID}  

---
**Runtime:** Set to GPU (Runtime → Change runtime type → T4 GPU)

## 📦 Cell 1 — Install dependencies
"""

# Install Flower with simulation support
!pip install -q -U 'flwr[simulation]' torch torchvision matplotlib pandas seaborn
print('✅ All packages installed')

pip install -U flwr protobuf==5.29.1

"""## 🔧 Cell 2 — Imports & Seed"""

# ── Standard imports ──────────────────────────────────────────────────────
import os, math, time, random, warnings, copy
from collections import OrderedDict
from typing import Dict, List, Optional, Tuple, Union

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
warnings.filterwarnings('ignore')

# ── PyTorch ───────────────────────────────────────────────────────────────
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Subset
from torchvision import datasets, transforms

# ── Flower ────────────────────────────────────────────────────────────────
import flwr as fl
from flwr.common import (
    EvaluateIns, EvaluateRes, FitIns, FitRes,
    Parameters, Scalar,
    ndarrays_to_parameters, parameters_to_ndarrays,
)
from flwr.server.client_manager import ClientManager
from flwr.server.client_proxy import ClientProxy
from flwr.server.strategy import FedAvg
from flwr.server.strategy.aggregate import aggregate, weighted_loss_avg

# ── Fixed seeds (mandatory per course guidelines) ─────────────────────────
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'✅ Seeds set. Device: {DEVICE}')
print(f'   Flower version: {fl.__version__}')
print(f'   PyTorch version: {torch.__version__}')

"""## 🗂️ Cell 3 — Dataset loading & Dirichlet partitioning"""

# ─────────────────────────────────────────────────────────────────────────
#  TRANSFORMS
# ─────────────────────────────────────────────────────────────────────────
TRANSFORMS = {
    'mnist':   transforms.Compose([transforms.ToTensor(),
                                   transforms.Normalize((0.1307,), (0.3081,))]),
    'fmnist':  transforms.Compose([transforms.ToTensor(),
                                   transforms.Normalize((0.2860,), (0.3530,))]),
    'cifar10': transforms.Compose([transforms.ToTensor(),
                                   transforms.Normalize((0.4914,0.4822,0.4465),
                                                        (0.2023,0.1994,0.2010))]),
}

def load_dataset(name: str):
    """Download and return (train_dataset, test_dataset)."""
    t = TRANSFORMS[name]
    if name == 'mnist':
        return (datasets.MNIST('./data', train=True,  download=True, transform=t),
                datasets.MNIST('./data', train=False, download=True, transform=t))
    elif name == 'fmnist':
        return (datasets.FashionMNIST('./data', train=True,  download=True, transform=t),
                datasets.FashionMNIST('./data', train=False, download=True, transform=t))
    elif name == 'cifar10':
        return (datasets.CIFAR10('./data', train=True,  download=True, transform=t),
                datasets.CIFAR10('./data', train=False, download=True, transform=t))

# ─────────────────────────────────────────────────────────────────────────
#  DIRICHLET PARTITIONING
# ─────────────────────────────────────────────────────────────────────────
def dirichlet_partition(dataset, num_clients: int, alpha,
                        seed: int = 42, min_samples: int = 10) -> List[List[int]]:
    """
    Partition dataset indices using Dirichlet(alpha).
    alpha='iid' or None → uniform IID split.
    Small alpha (0.01) → extreme non-IID.
    min_samples guarantees every client has at least this many samples
    (prevents empty-partition crashes with extreme alpha + many clients).
    """
    np.random.seed(seed)
    targets = np.array([dataset[i][1] for i in range(len(dataset))])
    num_classes = len(np.unique(targets))

    # IID fallback
    if alpha is None or str(alpha).lower() == 'iid':
        idx = np.random.permutation(len(dataset))
        return [s.tolist() for s in np.array_split(idx, num_clients)]

    # Build per-class index lists
    class_idx = {c: [] for c in range(num_classes)}
    for i, lbl in enumerate(targets):
        class_idx[lbl].append(i)
    for c in class_idx:
        np.random.shuffle(class_idx[c])

    client_idx: List[List[int]] = [[] for _ in range(num_clients)]
    for c in range(num_classes):
        props = np.random.dirichlet(np.repeat(alpha, num_clients))
        props = (np.cumsum(props) * len(class_idx[c])).astype(int)[:-1]
        for j, split in enumerate(np.split(class_idx[c], props)):
            client_idx[j].extend(split.tolist())

    for j in range(num_clients):
        np.random.shuffle(client_idx[j])

    # ✅ FIX 1: Guarantee every client has at least min_samples
    # Prevents DataLoader crash: "num_samples should be a positive integer, got 0"
    all_indices = [i for sub in client_idx for i in sub]
    for j in range(num_clients):
        if len(client_idx[j]) < min_samples:
            needed = min_samples - len(client_idx[j])
            extras = np.random.choice(all_indices, size=needed, replace=True).tolist()
            client_idx[j].extend(extras)

    return client_idx


def simulate_straggler_speeds(num_clients: int, straggler_ratio: float = 0.2,
                               seed: int = 42) -> List[float]:
    """Assign simulated compute speeds (Cat-7 system heterogeneity)."""
    rng = np.random.RandomState(seed)
    speeds = []
    for _ in range(num_clients):
        if rng.random() < straggler_ratio:
            speeds.append(float(rng.uniform(0.1, 0.4)))  # straggler
        else:
            speeds.append(float(rng.uniform(0.7, 1.0)))  # normal
    return speeds

print('✅ Data utilities defined')

"""## 🧠 Cell 4 — Model definitions"""

# ─────────────────────────────────────────────────────────────────────────
#  CNN for MNIST / FashionMNIST
# ─────────────────────────────────────────────────────────────────────────
class MnistCNN(nn.Module):
    def __init__(self, num_classes=10):
        super().__init__()
        self.conv1   = nn.Conv2d(1, 32, 3, padding=1)
        self.conv2   = nn.Conv2d(32, 64, 3, padding=1)
        self.pool    = nn.MaxPool2d(2, 2)
        # ✅ FIX 2: Removed nn.Dropout(0.25) — CUDA dropout triggers SIGFPE
        # (Floating Point Exception) when batch sizes are small/edge-case,
        # killing the Ray worker actor and crashing the entire simulation.
        self.fc1     = nn.Linear(64 * 7 * 7, 128)
        self.fc2     = nn.Linear(128, num_classes)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))   # 14×14
        x = self.pool(F.relu(self.conv2(x)))   # 7×7
        x = x.view(x.size(0), -1)
        x = F.relu(self.fc1(x))               # dropout removed here
        return self.fc2(x)


# ─────────────────────────────────────────────────────────────────────────
#  Small ResNet-style CNN for CIFAR-10
# ─────────────────────────────────────────────────────────────────────────
class ResBlock(nn.Module):
    def __init__(self, in_ch, out_ch, stride=1):
        super().__init__()
        self.conv1 = nn.Conv2d(in_ch, out_ch, 3, stride, 1, bias=False)
        self.bn1   = nn.BatchNorm2d(out_ch)
        self.conv2 = nn.Conv2d(out_ch, out_ch, 3, 1, 1, bias=False)
        self.bn2   = nn.BatchNorm2d(out_ch)
        self.skip  = nn.Sequential()
        if stride != 1 or in_ch != out_ch:
            self.skip = nn.Sequential(
                nn.Conv2d(in_ch, out_ch, 1, stride, bias=False),
                nn.BatchNorm2d(out_ch))
    def forward(self, x):
        return F.relu(self.bn2(self.conv2(F.relu(self.bn1(self.conv1(x))))) + self.skip(x))

class CifarCNN(nn.Module):
    def __init__(self, num_classes=10):
        super().__init__()
        self.prep   = nn.Sequential(nn.Conv2d(3,64,3,1,1,bias=False), nn.BatchNorm2d(64), nn.ReLU())
        self.layer1 = ResBlock(64,  128, stride=2)
        self.layer2 = ResBlock(128, 256, stride=2)
        self.layer3 = ResBlock(256, 512, stride=2)
        self.pool   = nn.AdaptiveAvgPool2d(1)
        self.fc     = nn.Linear(512, num_classes)
    def forward(self, x):
        x = self.layer3(self.layer2(self.layer1(self.prep(x))))
        return self.fc(self.pool(x).view(x.size(0), -1))


def get_model(dataset_name: str) -> nn.Module:
    name = dataset_name.lower()
    if   name in ('mnist', 'fmnist'): return MnistCNN(10)
    elif name == 'cifar10':           return CifarCNN(10)
    else: raise ValueError(f'No model for {name}')

def get_params(model):   return [v.cpu().numpy() for _, v in model.state_dict().items()]
def set_params(model, params):
    sd = OrderedDict({k: torch.tensor(v) for k, v in zip(model.state_dict().keys(), params)})
    model.load_state_dict(sd, strict=True)

def model_size_mb(model): return sum(p.numel() for p in model.parameters()) * 4 / 1024**2

# Quick sanity check
m = get_model('mnist')
print(f'✅ Models defined | MNIST CNN size: {model_size_mb(m):.2f} MB')
print(f'   CIFAR CNN size: {model_size_mb(get_model("cifar10")):.2f} MB')

"""## 🤝 Cell 5 — Flower Client (OortClient)"""

class OortClient(fl.client.NumPyClient):
    """
    Flower NumPyClient that:
      1. Trains locally with SGD (per course guidelines)
      2. Reports training loss back → used by OortStrategy for utility scoring
      3. Simulates system heterogeneity via compute_speed
    """

    def __init__(self, cid: int, train_indices: List[int],
                 train_dataset, test_dataset,
                 dataset_name: str, compute_speed: float = 1.0):
        self.cid           = cid
        self.train_indices = train_indices
        self.train_dataset = train_dataset
        self.test_dataset  = test_dataset
        self.dataset_name  = dataset_name
        self.compute_speed = compute_speed
        self.model         = get_model(dataset_name).to(DEVICE)

    def get_parameters(self, config):
        return get_params(self.model)

    def fit(self, parameters, config):
        set_params(self.model, parameters)

        # ✅ FIX 3a: Skip training entirely if client has no data
        # (can happen with extreme Dirichlet alpha + many clients)
        if len(self.train_indices) == 0:
            return get_params(self.model), 0, {
                'train_loss':    0.0,
                'train_samples': 0,
                'compute_speed': self.compute_speed,
                'client_id':     self.cid,
            }

        self.model.train()

        epochs     = int(config.get('local_epochs', 5))
        batch_size = int(config.get('batch_size',   32))
        lr         = float(config.get('lr',          0.01))

        # ✅ FIX 3b: Clamp batch_size so it never exceeds available samples
        # Prevents DataLoader RandomSampler from crashing on tiny partitions
        batch_size = min(batch_size, len(self.train_indices))

        loader    = DataLoader(Subset(self.train_dataset, self.train_indices),
                               batch_size=batch_size, shuffle=True)
        optimizer = torch.optim.SGD(self.model.parameters(), lr=lr, momentum=0.9)
        criterion = nn.CrossEntropyLoss()

        last_loss = 0.0
        for epoch in range(epochs):
            running_loss, n = 0.0, 0
            for x, y in loader:
                x, y = x.to(DEVICE), y.to(DEVICE)
                optimizer.zero_grad()
                loss = criterion(self.model(x), y)
                loss.backward()
                optimizer.step()
                running_loss += loss.item() * len(y)
                n += len(y)
            last_loss = running_loss / max(n, 1)

        return get_params(self.model), len(self.train_indices), {
            # Oort needs these metrics for utility scoring
            'train_loss':    float(last_loss),
            'train_samples': len(self.train_indices),
            'compute_speed': self.compute_speed,
            'client_id':     self.cid,
        }

    def evaluate(self, parameters, config):
        set_params(self.model, parameters)
        self.model.eval()
        loader    = DataLoader(self.test_dataset, batch_size=256, shuffle=False)
        criterion = nn.CrossEntropyLoss()
        loss, correct, total = 0.0, 0, 0
        with torch.no_grad():
            for x, y in loader:
                x, y = x.to(DEVICE), y.to(DEVICE)
                out   = self.model(x)
                loss += criterion(out, y).item() * len(y)
                correct += (out.argmax(1) == y).sum().item()
                total   += len(y)
        return float(loss/max(total,1)), total, {'accuracy': float(correct/max(total,1))}

print('✅ OortClient defined')

"""## ⚙️ Cell 6 — Oort Strategy (core algorithm)"""

class OortStrategy(FedAvg):
    """
    Oort guided participant selection (Lai et al., OSDI 2021).

    Three core mechanisms:
      1. Statistical utility  = loss × √(num_samples)   [Eq.1 in paper]
      2. System utility       = penalty for slow clients
      3. Exploration bonus    = UCB-style boost for under-selected clients

    Selection: score all clients → pick top K×(1+ε) pool → softmax sample K.
    Pacer: every `pacer_step` rounds, relax the system deadline to admit
           slower-but-useful clients.
    """

    def __init__(self, num_clients_per_round: int = 10,
                 exploration_factor: float = 0.2,
                 pacer_step: int = 5, pacer_delta: float = 0.05,
                 decay: float = 0.9, clip_loss: float = 5.0,
                 **fedavg_kwargs):
        super().__init__(**fedavg_kwargs)
        self.K            = num_clients_per_round
        self.epsilon      = exploration_factor
        self.pacer_step   = pacer_step
        self.pacer_delta  = pacer_delta
        self.decay        = decay
        self.clip_loss    = clip_loss

        # Per-client state
        self._stat:     Dict[str, float] = {}   # statistical utility
        self._sys:      Dict[str, float] = {}   # system utility
        self._last_sel: Dict[str, int]   = {}   # last round selected
        self._n_sel:    Dict[str, int]   = {}   # times selected

        self._deadline    = 1.0   # system-speed threshold (Pacer)
        self._cur_round   = 0

        # For results tracking
        self.history: List[Dict] = []

    # ── Utility functions ────────────────────────────────────────────────
    def _stat_util(self, loss, n_samples):
        return min(loss, self.clip_loss) * math.sqrt(n_samples)

    def _sys_util(self, speed):
        return min(self._deadline / max(speed, 1e-6), 1.0)

    def _explore_bonus(self, cid, rnd):
        n = self._n_sel.get(cid, 0)
        return 1.0 if n == 0 else math.sqrt(math.log(rnd + 1) / n)

    def _temporal_decay(self, cid, rnd):
        return self.decay ** (rnd - self._last_sel.get(cid, 0))

    def _score(self, cid, rnd):
        stat  = self._stat.get(cid, 1.0)
        sys   = self._sys.get(cid, 1.0)
        expl  = self._explore_bonus(cid, rnd)
        td    = self._temporal_decay(cid, rnd)
        return stat * sys * expl * td

    # ── Flower hooks ─────────────────────────────────────────────────────
    def configure_fit(self, server_round, parameters, client_manager):
        self._cur_round = server_round

        # Pacer: relax deadline every pacer_step rounds
        if server_round > 0 and server_round % self.pacer_step == 0:
            self._deadline = min(1.0, self._deadline + self.pacer_delta)

        config  = {'local_epochs': 5, 'batch_size': 32, 'lr': 0.01,
                   'server_round': server_round}
        fit_ins = FitIns(parameters, config)

        all_clients = list(client_manager.all().values())
        n_available = len(all_clients)
        k = min(self.K, n_available)

        # Warm-up: random selection until we have utility scores
        if len(self._stat) < max(1, k):
            chosen = np.random.choice(all_clients, size=k, replace=False).tolist()
            return [(c, fit_ins) for c in chosen]

        # Score all clients
        scored = sorted(
            [(c, self._score(c.cid, server_round)) for c in all_clients],
            key=lambda x: x[1], reverse=True
        )

        # Exploration-exploitation pool
        pool_size  = min(int(k * (1 + self.epsilon)), n_available)
        pool       = [c for c, _ in scored[:pool_size]]
        pool_scores= np.array([s for _, s in scored[:pool_size]], dtype=float)

        # Softmax-weighted sampling from pool
        pool_scores -= pool_scores.max()          # numerical stability
        weights = np.exp(pool_scores)
        weights /= weights.sum()
        chosen_idx = np.random.choice(len(pool), size=k, replace=False, p=weights)
        chosen = [pool[i] for i in chosen_idx]
        return [(c, fit_ins) for c in chosen]

    def aggregate_fit(self, server_round, results, failures):
        if not results:
            return None, {}

        # Update per-client utility scores
        for client, fit_res in results:
            cid     = client.cid
            m       = fit_res.metrics or {}
            loss    = float(m.get('train_loss',    1.0))
            samples = int(  m.get('train_samples', 1))
            speed   = float(m.get('compute_speed', 1.0))

            self._stat[cid]     = self._stat_util(loss, samples)
            self._sys[cid]      = self._sys_util(speed)
            self._last_sel[cid] = server_round
            self._n_sel[cid]    = self._n_sel.get(cid, 0) + 1

        # FedAvg weighted aggregation
        weight_res = [(parameters_to_ndarrays(r.parameters), r.num_examples)
                      for _, r in results]
        agg_params = ndarrays_to_parameters(aggregate(weight_res))

        # Round-level metrics
        avg_loss = np.mean([float(r.metrics.get('train_loss', 0)) for _, r in results])
        avg_spd  = np.mean([float(r.metrics.get('compute_speed', 1)) for _, r in results])
        strag    = np.mean([1.0 if float(r.metrics.get('compute_speed',1)) < 0.5
                            else 0.0 for _, r in results])

        self.history.append({
            'round':           server_round,
            'num_selected':    len(results),
            'avg_train_loss':  float(avg_loss),
            'avg_speed':       float(avg_spd),
            'straggler_ratio': float(strag),
            'pacer_deadline':  float(self._deadline),
        })

        return agg_params, {'avg_train_loss': float(avg_loss),
                            'straggler_ratio': float(strag)}

    def aggregate_evaluate(self, server_round, results, failures):
        if not results:
            return None, {}
        loss = weighted_loss_avg([(r.num_examples, r.loss) for _, r in results])
        acc  = float(np.mean([float(r.metrics.get('accuracy', 0)) for _, r in results]))
        return loss, {'accuracy': acc}

print('✅ OortStrategy defined')

"""## 🚀 Cell 7 — Simulation runner (shared by Oort & FedAvg)"""

def run_experiment(
    dataset_name:    str   = 'mnist',
    num_clients:     int   = 50,
    alpha                  = 0.01,    # Dirichlet alpha or 'iid'
    num_rounds:      int   = 50,
    strategy_name:   str   = 'oort', # 'oort' or 'fedavg'
    straggler_ratio: float = 0.2,
    num_cpus:        float = 1.0,
    num_gpus:        float = 0.0,    # set >0 if Colab has GPU
):
    """
    Run a full FL simulation with either Oort or FedAvg strategy.
    Returns (history_df, strategy_object, model_size_mb).
    """
    print(f'\n{'='*65}')
    print(f'  Strategy={strategy_name.upper()} | Dataset={dataset_name.upper()} | '
          f'Clients={num_clients} | α={alpha} | Rounds={num_rounds}')
    print(f'{'='*65}')

    # ── Load & partition data ────────────────────────────────────────────
    train_ds, test_ds = load_dataset(dataset_name)
    client_indices    = dirichlet_partition(train_ds, num_clients, alpha)
    client_speeds     = simulate_straggler_speeds(num_clients, straggler_ratio)

    model_mb = model_size_mb(get_model(dataset_name))
    k_per_round = max(1, int(num_clients * 0.5))  # 50% per round

    # ── Global test evaluation fn (server-side, every round) ────────────
    def get_evaluate_fn():
        def evaluate_fn(server_round, params, config):
            model = get_model(dataset_name).to(DEVICE)
            set_params(model, params)
            model.eval()
            loader    = DataLoader(test_ds, batch_size=256, shuffle=False)
            criterion = nn.CrossEntropyLoss()
            loss, correct, total = 0.0, 0, 0
            with torch.no_grad():
                for x, y in loader:
                    x, y = x.to(DEVICE), y.to(DEVICE)
                    out   = model(x)
                    loss += criterion(out, y).item() * len(y)
                    correct += (out.argmax(1) == y).sum().item()
                    total   += len(y)
            acc  = correct / max(total, 1)
            return float(loss / max(total, 1)), {'accuracy': float(acc)}
        return evaluate_fn

    # ── Metrics aggregation fns ──────────────────────────────────────────
    def fit_metrics_agg(metrics):
        losses = [n * m.get('train_loss', 0) for n, m in metrics]
        total  = sum(n for n, _ in metrics)
        return {'avg_train_loss': sum(losses) / max(total, 1)}

    def eval_metrics_agg(metrics):
        accs  = [n * m.get('accuracy', 0) for n, m in metrics]
        total = sum(n for n, _ in metrics)
        return {'accuracy': sum(accs) / max(total, 1)}

    # ── Strategy ────────────────────────────────────────────────────────
    common_kwargs = dict(
        fraction_fit=0.5,
        fraction_evaluate=0.5,
        min_fit_clients=k_per_round,
        min_evaluate_clients=max(1, k_per_round // 2),
        min_available_clients=num_clients,
        evaluate_fn=get_evaluate_fn(),
        fit_metrics_aggregation_fn=fit_metrics_agg,
        evaluate_metrics_aggregation_fn=eval_metrics_agg,
    )

    if strategy_name.lower() == 'oort':
        strategy = OortStrategy(
            num_clients_per_round=k_per_round,
            exploration_factor=0.2,
            pacer_step=5,
            pacer_delta=0.05,
            decay=0.9,
            **common_kwargs,
        )
    else:
        strategy = FedAvg(**common_kwargs)

    # ── Client factory fn ────────────────────────────────────────────────
    def client_fn(cid: str):
        idx   = int(cid)
        speed = client_speeds[idx]
        return OortClient(
            cid=idx,
            train_indices=client_indices[idx],
            train_dataset=train_ds,
            test_dataset=test_ds,
            dataset_name=dataset_name,
            compute_speed=speed,
        )

    # ── Run simulation ───────────────────────────────────────────────────
    history = fl.simulation.start_simulation(
        client_fn=client_fn,
        num_clients=num_clients,
        config=fl.server.ServerConfig(num_rounds=num_rounds),
        strategy=strategy,
        client_resources={'num_cpus': num_cpus, 'num_gpus': num_gpus},
        ray_init_args={'ignore_reinit_error': True, 'include_dashboard': False},
    )

    # ── Build results DataFrame ──────────────────────────────────────────
    rounds     = [r for r, _ in history.metrics_centralized.get('accuracy', [])]
    accs       = [float(v) for _, v in history.metrics_centralized.get('accuracy', [])]
    losses_cen = [float(v) for _, v in history.losses_centralized]

    # Pad if lengths differ (round 0 may have extra entry)
    min_len = min(len(rounds), len(accs), len(losses_cen))

    comm_cost_mb = model_mb * k_per_round * 2  # upload + download per round
    df = pd.DataFrame({
        'round':        rounds[:min_len],
        'accuracy':     accs[:min_len],
        'loss':         losses_cen[:min_len],
        'strategy':     strategy_name.upper(),
        'dataset':      dataset_name.upper(),
        'num_clients':  num_clients,
        'alpha':        str(alpha),
        'comm_cost_mb': [comm_cost_mb * (i+1) for i in range(min_len)],
    })

    # Convergence round (first round ≥ 80% accuracy)
    conv_rounds = df[df['accuracy'] >= 0.80]
    conv_round  = int(conv_rounds['round'].iloc[0]) if len(conv_rounds) > 0 else -1
    final_acc   = float(df['accuracy'].iloc[-1]) if len(df) > 0 else 0.0
    total_comm  = float(df['comm_cost_mb'].iloc[-1]) if len(df) > 0 else 0.0

    print(f'\n  ✅ Done! Final accuracy: {final_acc:.4f} | '
          f'Convergence round (≥80%): {conv_round} | '
          f'Total comm: {total_comm:.1f} MB')

    return df, strategy, model_mb

print('✅ run_experiment() defined')

"""## 🧪 Cell 8 — Run experiments
### Configure which experiments to run here
"""

import pandas as pd

# ── EXPERIMENT CONFIGURATION ──────────────────────────────────────────────
NUM_ROUNDS      = 50
NUM_CLIENTS     = 50
ALPHA           = 0.5
DATASET         = 'mnist'
STRAGGLER_RATIO = 0.2
NUM_GPUS_CLIENT = 0.2 if torch.cuda.is_available() else 0.0

all_results = []

# ── Run Oort ─────────────────────────────────────────────────────────────
df_oort, strat_oort, model_mb = run_experiment(
    dataset_name=DATASET,
    num_clients=NUM_CLIENTS,
    alpha=ALPHA,
    num_rounds=NUM_ROUNDS,
    strategy_name='oort',
    straggler_ratio=STRAGGLER_RATIO,
    num_gpus=NUM_GPUS_CLIENT,
)

# Add strategy name column (optional but useful)
df_oort["Strategy"] = "Oort"

all_results.append(df_oort)

# ── COMBINE RESULTS ──────────────────────────────────────────────────────
df_all = pd.concat(all_results, ignore_index=True)

print(f'\n✅ Experiments complete! Total rows: {len(df_all)}')

# ── SAVE CSV ─────────────────────────────────────────────────────────────
file_name = "oort_100_rounds_full_results.csv"
df_all.to_csv(file_name, index=False)

print(f"📁 CSV saved as: {file_name}")

# ── DOWNLOAD (COLAB) ─────────────────────────────────────────────────────
from google.colab import files
files.download(file_name)